=== xen-project/xen/tools/security/policies/security_policy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Author: Ray Valdez, Reiner Sailer {rvaldez,sailer}@us.ibm.com -->
<!--         This file defines the schema, which is used to define -->
<!--         the security policy and the security labels in Xen.    -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ibm.com" xmlns="http://www.ibm.com" elementFormDefault="qualified">
	<xsd:element name="SecurityPolicyDefinition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="PolicyHeader" minOccurs="1" maxOccurs="1"></xsd:element>
				<xsd:element ref="SimpleTypeEnforcement" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="ChineseWall" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="SecurityLabelTemplate" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="PolicyHeader">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="PolicyName" minOccurs="1" maxOccurs="1" type="xsd:string"></xsd:element>
				<xsd:element name="PolicyUrl" minOccurs="0" maxOccurs="1" type="xsd:string"></xsd:element>
				<xsd:element name="Reference" type="xsd:string" minOccurs="0" maxOccurs="1" />
				<xsd:element name="Date" minOccurs="0" maxOccurs="1" type="xsd:string"></xsd:element>
				<xsd:element name="NameSpaceUrl" minOccurs="0" maxOccurs="1" type="xsd:string"></xsd:element>
				<xsd:element name="Version" minOccurs="0" maxOccurs="1" type="VersionFormat"/>
				<xsd:element ref="FromPolicy" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="ChineseWall">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="ChineseWallTypes" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="ConflictSets" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="priority" type="PolicyOrder" use="optional"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="SimpleTypeEnforcement">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="SimpleTypeEnforcementTypes" />
			</xsd:sequence>
			<xsd:attribute name="priority" type="PolicyOrder" use="optional"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="SecurityLabelTemplate">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="SubjectLabels" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="VirtualMachineLabel" minOccurs="1" maxOccurs="unbounded"></xsd:element>
						</xsd:sequence>
						<xsd:attribute name="bootstrap" type="xsd:string" use="required"></xsd:attribute>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="ObjectLabels" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="ResourceLabel" minOccurs="1" maxOccurs="unbounded"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="ChineseWallTypes">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="1" ref="Type" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="ConflictSets">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="1" ref="Conflict" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="SimpleTypeEnforcementTypes">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="1" ref="Type" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Conflict">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="1" ref="Type" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="optional"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="VirtualMachineLabel">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Name"></xsd:element>
				<xsd:element ref="SimpleTypeEnforcementTypes" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="ChineseWallTypes" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="ResourceLabel">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Name"></xsd:element>
				<xsd:element ref="SimpleTypeEnforcementTypes" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Name" type="xsd:string" />
	<xsd:element name="Type" type="xsd:string" />
	<xsd:simpleType name="PolicyOrder">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="PrimaryPolicyComponent"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="FromPolicy">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="PolicyName" minOccurs="1" maxOccurs="1" type="xsd:string"/>
				<xsd:element name="Version" minOccurs="1" maxOccurs="1" type="VersionFormat"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="VersionFormat">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]{1,8}.[0-9]{1,8}"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== xen-project/xen/tools/xm-test/tests/security-acm/xm-test-new-security_policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by ezPolicy        -->
<SecurityPolicyDefinition xmlns="http://www.ibm.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com ../../security_policy.xsd ">
    <PolicyHeader>
        <PolicyName>xm-test</PolicyName>
        <Date>Fri Sep 29 14:44:38 2006</Date>
        <Version>1.1</Version>
        <FromPolicy>
            <PolicyName>xm-test</PolicyName>
            <Version>1.0</Version>
        </FromPolicy>
    </PolicyHeader>

    <SimpleTypeEnforcement>
        <SimpleTypeEnforcementTypes>
            <Type>SystemManagement</Type>
            <Type>green</Type>
            <Type>red</Type>
        </SimpleTypeEnforcementTypes>
    </SimpleTypeEnforcement>

    <ChineseWall priority="PrimaryPolicyComponent">
        <ChineseWallTypes>
            <Type>SystemManagement</Type>
            <Type>green</Type>
            <Type>red</Type>
        </ChineseWallTypes>

        <ConflictSets>
            <Conflict name="RER">
                <Type>green</Type>
                <Type>red</Type>
            </Conflict>
       </ConflictSets>
    </ChineseWall>

    <SecurityLabelTemplate>
        <SubjectLabels bootstrap="SystemManagement">
            <VirtualMachineLabel>
                <Name>SystemManagement</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>SystemManagement</Type>
                    <Type>green</Type>
                    <Type>red</Type>
                </SimpleTypeEnforcementTypes>
                <ChineseWallTypes>
                    <Type>SystemManagement</Type>
                </ChineseWallTypes>
            </VirtualMachineLabel>

            <VirtualMachineLabel>
                <Name>green</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>green</Type>
                </SimpleTypeEnforcementTypes>
                <ChineseWallTypes>
                    <Type>green</Type>
                </ChineseWallTypes>
            </VirtualMachineLabel>

            <VirtualMachineLabel>
                <Name>red</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>red</Type>
                </SimpleTypeEnforcementTypes>
                <ChineseWallTypes>
                    <Type>red</Type>
                </ChineseWallTypes>
            </VirtualMachineLabel>

        </SubjectLabels>

        <ObjectLabels>
            <ResourceLabel>
                <Name>SystemManagement</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>SystemManagement</Type>
                </SimpleTypeEnforcementTypes>
            </ResourceLabel>

            <ResourceLabel>
                <Name>green</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>green</Type>
                </SimpleTypeEnforcementTypes>
            </ResourceLabel>

            <ResourceLabel>
                <Name>red</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>red</Type>
                </SimpleTypeEnforcementTypes>
            </ResourceLabel>

        </ObjectLabels>
    </SecurityLabelTemplate>
</SecurityPolicyDefinition>

=== xen-project/xen/tools/security/policies/example/client_v1-security_policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Author: Reiner Sailer, Ray Valdez {sailer,rvaldez}@us.ibm.com  -->
<!--             This file defines the security policies, which     -->
<!--             can be enforced by the Xen Access Control Module.  -->
<!--             Currently: Chinese Wall and Simple Type Enforcement-->
<SecurityPolicyDefinition xmlns="http://www.ibm.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com ../../security_policy.xsd ">
	<PolicyHeader>
		<PolicyName>example.client_v1</PolicyName>
		<PolicyUrl>www.ibm.com/example/client_v1</PolicyUrl>
		<Date>2006-03-31</Date>
		<Version>1.0</Version>
	</PolicyHeader>
	<!--                                                        -->
	<!-- example of a simple type enforcement policy definition -->
	<!--                                                        -->
	<SimpleTypeEnforcement>
		<SimpleTypeEnforcementTypes>
			<Type>ste_SystemManagement</Type><!-- machine/security management -->
			<Type>ste_PersonalFinances</Type><!-- personal finances -->
			<Type>ste_InternetInsecure</Type><!-- games, active X, etc. -->
			<Type>ste_DonatedCycles</Type><!-- donation to BOINC/seti@home -->
			<Type>ste_PersistentStorageA</Type><!-- domain managing the harddrive A-->
			<Type>ste_NetworkAdapter0</Type><!-- type of the domain managing ethernet adapter 0-->
		</SimpleTypeEnforcementTypes>
	</SimpleTypeEnforcement>
	<!--                                             -->
	<!-- example of a chinese wall type definition   -->
	<!-- along with its conflict sets                -->
	<!-- (typse in a confict set are exclusive, i.e. -->
	<!--  once a Domain with one type of a set is    -->
	<!--  running, no other Domain with another type -->
	<!--  of the same conflict set can start.)       -->
	<ChineseWall priority="PrimaryPolicyComponent">
		<ChineseWallTypes>
			<Type>cw_SystemManagement</Type>
			<Type>cw_Sensitive</Type>
			<Type>cw_Isolated</Type>
			<Type>cw_Distrusted</Type>
		</ChineseWallTypes>

		<ConflictSets>
			<Conflict name="Protection1">
				<Type>cw_Sensitive</Type>
				<Type>cw_Distrusted</Type>
			</Conflict>
		</ConflictSets>
	</ChineseWall>
	<SecurityLabelTemplate>
		<SubjectLabels bootstrap="dom_SystemManagement">
			<!-- single ste typed domains            -->
			<!-- ACM enforces that only domains with -->
			<!-- the same type can share information -->
			<!--                                     -->
			<!-- Bootstrap label is assigned to Dom0 -->
			<VirtualMachineLabel>
				<Name>dom_HomeBanking</Name>
				<SimpleTypeEnforcementTypes>
					<Type>ste_PersonalFinances</Type>
				</SimpleTypeEnforcementTypes>

				<ChineseWallTypes>
					<Type>cw_Sensitive</Type>
				</ChineseWallTypes>
			</VirtualMachineLabel>

			<VirtualMachineLabel>
				<Name>dom_Fun</Name>
				<SimpleTypeEnforcementTypes>
					<Type>ste_InternetInsecure</Type>
				</SimpleTypeEnforcementTypes>

				<ChineseWallTypes>
					<Type>cw_Distrusted</Type>
				</ChineseWallTypes>
			</VirtualMachineLabel>

			<VirtualMachineLabel>
				<!-- donating some cycles to seti@home -->
				<Name>dom_BoincClient</Name>
				<SimpleTypeEnforcementTypes>
					<Type>ste_DonatedCycles</Type>
				</SimpleTypeEnforcementTypes>

				<ChineseWallTypes>
					<Type>cw_Isolated</Type>
				</ChineseWallTypes>
			</VirtualMachineLabel>

			<!-- Domains with multiple ste types services; such domains   -->
			<!-- must keep the types inside their domain safely confined. -->
			<VirtualMachineLabel>
				<Name>dom_SystemManagement</Name>
				<SimpleTypeEnforcementTypes>
					<!-- since dom0 needs access to every domain and -->
					<!-- resource right now ... -->
					<Type>ste_SystemManagement</Type>
					<Type>ste_PersonalFinances</Type>
					<Type>ste_InternetInsecure</Type>
					<Type>ste_DonatedCycles</Type>
					<Type>ste_PersistentStorageA</Type>
					<Type>ste_NetworkAdapter0</Type>
				</SimpleTypeEnforcementTypes>

				<ChineseWallTypes>
					<Type>cw_SystemManagement</Type>
				</ChineseWallTypes>
			</VirtualMachineLabel>

			<VirtualMachineLabel>
				<!-- serves persistent storage to other domains -->
				<Name>dom_StorageDomain</Name>
				<SimpleTypeEnforcementTypes>
					<!-- access right to the resource (hard drive a) -->
					<Type>ste_PersistentStorageA</Type>
					<!-- can serve following types -->
					<Type>ste_PersonalFinances</Type>
					<Type>ste_InternetInsecure</Type>
				</SimpleTypeEnforcementTypes>

				<ChineseWallTypes>
					<Type>cw_SystemManagement</Type>
				</ChineseWallTypes>
			</VirtualMachineLabel>

			<VirtualMachineLabel>
				<!-- serves network access to other domains -->
				<Name>dom_NetworkDomain</Name>
				<SimpleTypeEnforcementTypes>
					<!-- access right to the resource (ethernet card) -->
					<Type>ste_NetworkAdapter0</Type>
					<!-- can serve following types -->
					<Type>ste_PersonalFinances</Type>
					<Type>ste_InternetInsecure</Type>
					<Type>ste_DonatedCycles</Type>
				</SimpleTypeEnforcementTypes>

				<ChineseWallTypes>
					<Type>cw_SystemManagement</Type>
				</ChineseWallTypes>
			</VirtualMachineLabel>
		</SubjectLabels>

		<ObjectLabels>
			<ResourceLabel>
				<Name>res_ManagementResource</Name>
				<SimpleTypeEnforcementTypes>
					<Type>ste_SystemManagement</Type>
				</SimpleTypeEnforcementTypes>
			</ResourceLabel>

			<ResourceLabel>
				<Name>res_HardDrive(hda)</Name>
				<SimpleTypeEnforcementTypes>
					<Type>ste_PersistentStorageA</Type>
				</SimpleTypeEnforcementTypes>
			</ResourceLabel>

			<ResourceLabel>
				<Name>res_LogicalDiskPartition1(hda1)</Name>
				<SimpleTypeEnforcementTypes>
					<Type>ste_PersonalFinances</Type>
				</SimpleTypeEnforcementTypes>
			</ResourceLabel>

			<ResourceLabel>
				<Name>res_LogicalDiskPartition2(hda2)</Name>
				<SimpleTypeEnforcementTypes>
					<Type>ste_InternetInsecure</Type>
				</SimpleTypeEnforcementTypes>
			</ResourceLabel>

			<ResourceLabel>
				<Name>res_EthernetCard</Name>
				<SimpleTypeEnforcementTypes>
					<Type>ste_NetworkAdapter0</Type>
				</SimpleTypeEnforcementTypes>
			</ResourceLabel>

			<ResourceLabel>
				<Name>res_SecurityToken</Name>
				<SimpleTypeEnforcementTypes>
					<Type>ste_PersonalFinances</Type>
				</SimpleTypeEnforcementTypes>
			</ResourceLabel>

			<ResourceLabel>
				<Name>res_GraphicsAdapter</Name>
				<SimpleTypeEnforcementTypes>
					<Type>ste_SystemManagement</Type>
				</SimpleTypeEnforcementTypes>
			</ResourceLabel>
		</ObjectLabels>
	</SecurityLabelTemplate>
</SecurityPolicyDefinition>

=== xen-project/xen/tools/xm-test/tests/security-acm/xm-test-security_policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by ezPolicy        -->
<SecurityPolicyDefinition xmlns="http://www.ibm.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com ../../security_policy.xsd ">
    <PolicyHeader>
        <PolicyName>xm-test</PolicyName>
        <Date>Fri Sep 29 14:44:38 2006</Date>
    </PolicyHeader>

    <SimpleTypeEnforcement>
        <SimpleTypeEnforcementTypes>
            <Type>SystemManagement</Type>
            <Type>green</Type>
            <Type>red</Type>
            <Type>blue</Type>
        </SimpleTypeEnforcementTypes>
    </SimpleTypeEnforcement>

    <ChineseWall priority="PrimaryPolicyComponent">
        <ChineseWallTypes>
            <Type>SystemManagement</Type>
            <Type>green</Type>
            <Type>red</Type>
            <Type>blue</Type>
        </ChineseWallTypes>

        <ConflictSets>
            <Conflict name="RER">
                <Type>blue</Type>
                <Type>red</Type>
            </Conflict>
       </ConflictSets>
    </ChineseWall>

    <SecurityLabelTemplate>
        <SubjectLabels bootstrap="SystemManagement">
            <VirtualMachineLabel>
                <Name>SystemManagement</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>SystemManagement</Type>
                    <Type>green</Type>
                    <Type>red</Type>
                    <Type>blue</Type>
                </SimpleTypeEnforcementTypes>
                <ChineseWallTypes>
                    <Type>SystemManagement</Type>
                </ChineseWallTypes>
            </VirtualMachineLabel>

            <VirtualMachineLabel>
                <Name>green</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>green</Type>
                </SimpleTypeEnforcementTypes>
                <ChineseWallTypes>
                    <Type>green</Type>
                </ChineseWallTypes>
            </VirtualMachineLabel>

            <VirtualMachineLabel>
                <Name>red</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>red</Type>
                </SimpleTypeEnforcementTypes>
                <ChineseWallTypes>
                    <Type>red</Type>
                </ChineseWallTypes>
            </VirtualMachineLabel>

            <VirtualMachineLabel>
                <Name>blue</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>blue</Type>
                </SimpleTypeEnforcementTypes>
                <ChineseWallTypes>
                    <Type>blue</Type>
                </ChineseWallTypes>
            </VirtualMachineLabel>
        </SubjectLabels>

        <ObjectLabels>
            <ResourceLabel>
                <Name>SystemManagement</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>SystemManagement</Type>
                </SimpleTypeEnforcementTypes>
            </ResourceLabel>

            <ResourceLabel>
                <Name>green</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>green</Type>
                </SimpleTypeEnforcementTypes>
            </ResourceLabel>

            <ResourceLabel>
                <Name>red</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>red</Type>
                </SimpleTypeEnforcementTypes>
            </ResourceLabel>

            <ResourceLabel>
                <Name>blue</Name>
                <SimpleTypeEnforcementTypes>
                    <Type>blue</Type>
                </SimpleTypeEnforcementTypes>
            </ResourceLabel>
        </ObjectLabels>
    </SecurityLabelTemplate>
</SecurityPolicyDefinition>
